# Generated by Django 4.0 on 2022-01-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_remove_cartitem_subtotal_alter_cartitem_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
