# Generated by Django 4.0 on 2022-02-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_remove_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='plant.PNG', upload_to=''),
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
