# Generated by Django 4.0 on 2022-02-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_category_image_delete_categoryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='plant1.PNG', upload_to=''),
        ),
    ]
