# Generated by Django 4.0 on 2022-02-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='image',
            field=models.ImageField(default='indoor.jpg', upload_to=''),
        ),
        migrations.DeleteModel(
            name='PlantImage',
        ),
    ]
