# Generated by Django 4.0 on 2022-03-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_alter_plants_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_address',
            field=models.CharField(default='raniban-2,kathmandu', max_length=200),
            preserve_default=False,
        ),
    ]
