# Generated by Django 4.0 on 2022-03-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0011_orders_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
