# Generated by Django 4.0 on 2022-03-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
