# Generated by Django 4.0 on 2022-03-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_alter_orders_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantorder',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
