# Generated by Django 4.0 on 2022-06-04 07:14

from django.db import migrations, models
import plants.models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0018_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='plants',
            options={'verbose_name_plural': 'plants'},
        ),
        migrations.AlterField(
            model_name='plants',
            name='suitable_temperature',
            field=models.CharField(max_length=5, validators=[plants.models.validate_suitable_temperature]),
        ),
    ]
