# Generated by Django 4.0 on 2022-06-04 07:15

from django.db import migrations, models
import plants.models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0019_alter_category_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='suitable_temperature',
            field=models.CharField(max_length=10, validators=[plants.models.validate_suitable_temperature]),
        ),
    ]
