# Generated by Django 4.0 on 2022-06-04 07:17

from django.db import migrations, models
import plants.models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0020_alter_plants_suitable_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='suitable_temperature',
            field=models.CharField(max_length=20, validators=[plants.models.validate_suitable_temperature]),
        ),
    ]
